import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'sonner';
import './globals.css';
import { ConvexClientProvider } from './ConvexClientProvider';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  display: 'swap', // optional, improves loading behavior
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-screen">
        <ConvexClientProvider>
          {children}
          <Toaster richColors position="top-right" />
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  );
}
